apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-credentials
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pg-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: ${TEAM}/${ENVIRONMENT_STAGE}/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: ${TEAM}/${ENVIRONMENT_STAGE}/postgres
      property: password
  - secretKey: host
    remoteRef:
      key: ${TEAM}/${ENVIRONMENT_STAGE}/postgres
      property: host
  - secretKey: port
    remoteRef:
      key: ${TEAM}/${ENVIRONMENT_STAGE}/postgres
      property: port
  - secretKey: dbname
    remoteRef:
      key: ${TEAM}/${ENVIRONMENT_STAGE}/postgres
      property: dbname

