apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pg-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: ${RDS_SECRET_NAME}
        property: username
    - secretKey: password
      remoteRef:
        key: ${RDS_SECRET_NAME}
        property: password
    - secretKey: host
      remoteRef:
        key: ${RDS_SECRET_NAME}
        property: host
    - secretKey: port
      remoteRef:
        key: ${RDS_SECRET_NAME}
        property: port
    - secretKey: dbname
      remoteRef:
        key: ${RDS_SECRET_NAME}
        property: dbname

