# kafka-gitops/03-secrets/secretstore-aws.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "26"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: eso
            namespace: kafka
