apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  type: {{ .Values.service.type }}
  selector: { app: kafka-consumer }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

