# kafka-gitops/01-operators/argocd-app-external-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: kafka
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.1
    helm:
      releaseName: eso
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: eso
          annotations:
            eks.amazonaws.com/role-arn: ${ESO_IRSA_ROLE_ARN}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
