{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pyservice.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  tls:
    - hosts: [ "{{ .Values.ingress.host }}" ]       # kafka-dashboard-TEAM-dev.TEAM_DOMAIN
      secretName: {{ .Values.ingress.tlsSecret }}   # reuse your TLS setup
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "pyservice.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
