# kafka-gitops/app-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-bootstrap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: ${GITOPS_TARGET_REVISION}
    path: kafka-gitops/rendered/dev
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
