apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  source:
    repoURL: https://strimzi.github.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.43.0
    helm:
      valueFiles: [values.yaml]
  syncPolicy:
    automated: { prune: true, selfHeal: true }

