apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-credentials
  namespace: kafka
  annotations: { argocd.argoproj.io/sync-wave: "0" }
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pg-credentials
  data:
    - secretKey: DB_USER
      remoteRef: { key: <TEAM>/<ENV>/postgres, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: <TEAM>/<ENV>/postgres, property: password }
    - secretKey: DB_NAME
      remoteRef: { key: <TEAM>/<ENV>/postgres, property: dbname }
    - secretKey: DB_HOST
      remoteRef: { key: <TEAM>/<ENV>/postgres, property: host } # optional; can set via ConfigMap if not stored
