apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.2
    helm:
      values: |
        serviceAccount:
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ESO_IRSA_ROLE_NAME>
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy: { automated: { prune: true, selfHeal: true } }
