apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.48.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy: { automated: { prune: true, selfHeal: true } }
