apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: iot-kafka
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    version: 3.7.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: true
  entityOperator:
    topicOperator: {}
    userOperator: {}

