apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-1
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 3
  roles: ["controller","broker"]
  storage:
    type: persistent-claim
    class: gp3          # match your StorageClass name
    size: 100Gi
    deleteClaim: false
  template:
    pod:
      # match your Kafka nodegroup
      nodeSelector:
        workload: kafka
      tolerations:
        - key: "dedicated"
          value: "kafka"
          effect: "NoSchedule"

