image:
  repository: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${TEAM}/${ENVIRONMENT_STAGE}/kafka-producer
  tag: "1.0.0"
replicaCount: 1
env:
  KAFKA_BOOTSTRAP_SERVERS: iot-kafka-kafka-bootstrap.kafka.svc:9092

syncWave: "3"

