apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: iot-kafka
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    version: 4.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 20Gi
      class: gp3
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values: ["kafka"]
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
  zookeeper: # omitted in KRaft mode; Strimzi ignores this when KRaft enabled
    replicas: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}
