apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sensor-data
  namespace: kafka
  labels: { strimzi.io/cluster: iot-kafka }
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  partitions: 3
  replicas: 3
