apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-platform
  namespace: argocd
spec:
  project: kafka
  source:
    repoURL: https://github.com/timur178/my-playground.git
    targetRevision: HEAD
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
   automated: { prune: true, selfHeal: true }
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        