apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels: { app: kafka-producer }
  annotations:
    {{ include "syncWave" . }}
    argocd-image-updater.argoproj.io/image-list: |
      producer=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${TEAM}/${ENVIRONMENT_STAGE}/kafka-producer:~1
    argocd-image-updater.argoproj.io/update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: kafka-producer } }
  template:
    metadata:
      labels: { app: kafka-producer }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}

