apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels: { app: kafka-producer }
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: kafka-producer } }
  template:
    metadata:
      labels: { app: kafka-producer }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}

