name: Build & Push Docker Images

on:
  workflow_dispatch: {}
  push:
    branches: [ feature/battlefield ]
    paths:
      - "producer.py"
      - "consumer_api.py"
      - "dashboard.py"
      - "Dockerfile.*"
      - "gitops/apps/40-apps/**"
      - ".github/workflows/build-docker.yml"

env:
  AWS_REGION:        ${{ vars.AWS_REGION }}
  AWS_OIDC_ROLE_ARN: ${{ vars.AWS_OIDC_ROLE_ARN }}
  ECR_REGISTRY:      ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  ECR_REPO_PREFIX:   ${{ vars.TEAM }}/${{ vars.ENVIRONMENT_STAGE }}

jobs:
  docker-build-push:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        app:
          - name: kafka-producer
            dir: .
            dockerfile: Dockerfile.producer
            repo: kafka-producer
          - name: kafka-consumer
            dir: .
            dockerfile: Dockerfile.consumer
            repo: kafka-consumer
          - name: kafka-dashboard
            dir: .
            dockerfile: Dockerfile.dashboard
            repo: kafka-dashboard

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compute short SHA
        id: short
        run: echo "sha7=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Compose image name
        id: img
        run: |
          echo "name=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_PREFIX }}/${{ matrix.app.repo }}" >> "$GITHUB_OUTPUT"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.app.dir }}
          file: ${{ matrix.app.dockerfile }}
          push: true
          tags: |
            ${{ steps.img.outputs.name }}:${{ steps.short.outputs.sha7 }}
            ${{ steps.img.outputs.name }}:latest

