name: render-and-validate-gitops
on:
  push:
    paths:
      - "kafka-gitops/**"
      - ".github/workflows/gitops-validate.yaml"
  workflow_dispatch: {}

env:
  GITOPS_REPO_URL: ${{ vars.GITOPS_REPO_URL }}
  GITOPS_TARGET_REVISION: ${{ vars.GITOPS_TARGET_REVISION }}
  AWS_REGION:        ${{ vars.AWS_REGION }}
  ESO_IRSA_ROLE_ARN: ${{ vars.ESO_IRSA_ROLE_ARN }}
  RDS_SECRET_NAME:   ${{ vars.RDS_SECRET_NAME }}
  ACM_CERT_ARN:      ${{ vars.ACM_CERT_ARN }}

  # include ONLY if you install EBS CSI via Helm (not needed for EKS add-on)
  # EBS_CSI_IRSA_ROLE_ARN: ${{ vars.EBS_CSI_IRSA_ROLE_ARN }}

  # include ONLY if you also render values files that use these in hosts, etc.
  # TEAM:              ${{ vars.TEAM }}
  # TEAM_DOMAIN:       ${{ vars.TEAM_DOMAIN }}
  # ENVIRONMENT_STAGE: ${{ vars.ENVIRONMENT_STAGE }}

jobs:
  render:
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Render to kafka-gitops/rendered/dev
        run: |
          mkdir -p kafka-gitops/rendered/dev
          find kafka-gitops -maxdepth 3 -name '*.yaml' ! -path '*/rendered/*' -print0 \
            | xargs -0 -I {} sh -c 'mkdir -p kafka-gitops/rendered/dev/$(dirname "{}" | cut -d/ -f3-); envsubst < "{}" > kafka-gitops/rendered/dev/$(echo "{}" | cut -d/ -f3-)'

      - name: Fail if any ${VARS} remain after render
        run: |
          LEFT=$(grep -R '\${[A-Za-z_][A-Za-z0-9_]*}' kafka-gitops/rendered/dev || true)
          if [ -n "$LEFT" ]; then
            echo "ERROR: Unresolved placeholders remain:"
            echo "$LEFT"
            exit 1
          fi

      - name: Validate manifests (kubeconform)
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | tar xz
          ./kubeconform -summary -ignore-missing-schemas -strict kafka-gitops/rendered/dev

      - name: Commit rendered
        run: |
          git add kafka-gitops/rendered/dev || true
          git config user.name ci-bot
          git config user.email ci@example.com
          git commit -m "ci: render gitops for dev" || echo "no changes"
          git push || true
